version: "3"
services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile  # Aquí debe estar el Dockerfile correcto
    container_name: whatsapp-bot
    volumes:
      - ./session:/app/session
    ports:
      - 3000:3000
    restart: always
